AllCops:
  TargetRubyVersion: 3.3

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Disable Metrics/BlockLength for spec files
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
