name: Tests

on:
  push:
    branches:
      - main

jobs:
  rspec:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run Tests
        run: bundle exec rspec

  rubocop:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3

      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Run RuboCop
        run: bundle exec rubocop
